- name: send the environment variable
  template:
    dest: '~/result.sh'
    src: 'chess-env.sh.j2'
- name: change_the_file
  shell: sed -i -e :a -e "$!N;s/\n=/,/;ta" -e "P;D" /root/result.sh
- name: change "=," to "="
  shell: sed -i -e :a -e "$!N;s/=,/=/;ta" -e "P;D" /root/result.sh
- name: source the environment_variable
  shell: echo source ~/result.sh >> ~/.bashrc
- name: execute the entry.sh
  shell: sh /usr/local/.chess/scripts/entry.sh
