---

- name: Install PBSPro packages (mom)
  when: is_centos
  action: yum pkg={{item}} 
  with_items:
    - /scheduler/pbspro-execution-18.1.2-0.x86_64.rpm

- name: Check PBSPro config file 
  action: lineinfile dest=/etc/pbs.conf
          regexp='.*PBS_SERVER=.*'
          line='PBS_SERVER={{groups.pbspro_master[0]}}'
  notify: restart pbs

- name: Check PBSMom config file
  action: lineinfile dest=/var/spool/pbs/mom_priv/config
          regexp='.clienthost .*'
          line='$clienthost {{groups.pbspro_master[0]}}'
