---
- name: Setup scheduler repo 
  hosts: all
  roles:
    - role: 'nfs-client'
      file:
        path='/scheduler'
        state=directory
      NFS_MOUNTS:
        - fs: '{{user_client_ip}}:/scheduler'
          mountpoint: '/scheduler'
        

