---
#
# This playbook is for site-local customization to ElastiCluster's
# playbooks.  It runs *before* any other playbook distributed with
# ElastiCluster has gotten its chance to run (including the "common setup").
#
# An empty playbook is checked into the Git repository.  If you make
# any local modifications, please run `git update-index
# --assume-unchanged after.yml` to avoid committing them accidentally
# into ElastiCluster's main branch.
#
- name: Apply local customizations (before)
  tags:
    - before
    - local
  hosts: all
  # by default these are no-op (empty task list)
  roles: []
  tasks: 
    - name: Get internal repo for cluster
      get_url:
        url: 'http://mirrors.myhuaweicloud.com/repo/mirrors_source.sh'
        dest: '/etc/yum.repos.d/'
        validate_certs: '{{ not insecure_https_downloads|default("no")|bool }}'
    - name: Setup internal repo for cluster
      action: shell source /etc/yum.repos.d/mirrors_source.sh
